# Generated by Django 3.1.2 on 2020-12-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201203_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Programming/Technology'), ('2', 'Health/Fitness'), ('3', 'Personal'), ('4', 'Fashion'), ('5', 'Food'), ('6', 'Travel'), ('7', 'Business'), ('8', 'Art'), ('9', 'Other')], default='1', max_length=20),
        ),
    ]
