# Generated by Django 3.1.2 on 2020-12-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_favouritepost'),
        ('core', '0003_auto_20201203_1343'),
    ]

    operations = [
    ]
