# Generated by Django 3.1.2 on 2020-12-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20201203_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
