# Generated by Django 3.1.2 on 2020-12-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201208_2131'),
        ('core', '0009_post_tags'),
    ]

    operations = [
    ]
