# Generated by Django 3.0.8 on 2021-01-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='profile_pics'),
        ),
    ]
